name: learntoread
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.4
  wakelock: ^0.6.2
  fluttertoast: ^8.1.1
  flutter_rating_bar: ^4.0.1
  assets_audio_player: ^3.0.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/launcher_icons.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png" 
    icon_size: 48

flutter:

  uses-material-design: true

  fonts:
    - family: Kid Games
      fonts:
        - asset: fonts/KidGames.ttf

  assets:
    - audio/backsound.mp3
    - audio/congrats.mp3
    - assets/backgrounds.jpg
    - assets/backgrounds-item-page.jpg
    - assets/backgrounds-kuis.jpg
    - assets/icon1.png
    - assets/icon2.png
    - assets/icon3.png
    - assets/icon4.png
    - assets/icon5.png
    - assets/icon6.png
    - assets/kuis/A.png
    - assets/kuis/1.png
    - assets/kuis/red.png
    - assets/kuis/cat.png
    - assets/kuis/alif.png
    - assets/kuis/blue.png
    - assets/kuis/yellow.png
    - assets/kuis/elephant.png
    - assets/kuis/sho.png
    - assets/kuis/orange.png
    - assets/frame-kuis.svg
    - assets/button-menu.svg
    - assets/button-ulangi.svg
    - assets/accept.png
    - assets/timer.png
    - assets/log-out.png
    - assets/back.png
    - assets/next.png
    - assets/previous.png
    - assets/enable.png
    - assets/disable.png
    - assets/pengenalan-huruf/HURUF-A.png
    - assets/pengenalan-huruf/HURUF-B.png
    - assets/pengenalan-huruf/HURUF-C.png
    - assets/pengenalan-huruf/HURUF-D.png
    - assets/pengenalan-huruf/HURUF-E.png
    - assets/pengenalan-huruf/HURUF-F.png
    - assets/pengenalan-huruf/HURUF-G.png
    - assets/pengenalan-huruf/HURUF-H.png
    - assets/pengenalan-huruf/HURUF-I.png
    - assets/pengenalan-huruf/HURUF-J.png
    - assets/pengenalan-huruf/HURUF-K.png
    - assets/pengenalan-huruf/HURUF-L.png
    - assets/pengenalan-huruf/HURUF-M.png
    - assets/pengenalan-huruf/HURUF-N.png
    - assets/pengenalan-huruf/HURUF-O.png
    - assets/pengenalan-huruf/HURUF-P.png
    - assets/pengenalan-huruf/HURUF-Q.png
    - assets/pengenalan-huruf/HURUF-R.png
    - assets/pengenalan-huruf/HURUF-S.png
    - assets/pengenalan-huruf/HURUF-T.png
    - assets/pengenalan-huruf/HURUF-U.png
    - assets/pengenalan-huruf/HURUF-V.png
    - assets/pengenalan-huruf/HURUF-W.png
    - assets/pengenalan-huruf/HURUF-X.png
    - assets/pengenalan-huruf/HURUF-Y.png
    - assets/pengenalan-huruf/HURUF-Z.png
    - assets/pengenalan-angka/angka-0.png
    - assets/pengenalan-angka/angka-1.png
    - assets/pengenalan-angka/angka-2.png
    - assets/pengenalan-angka/angka-3.png
    - assets/pengenalan-angka/angka-4.png
    - assets/pengenalan-angka/angka-5.png
    - assets/pengenalan-angka/angka-6.png
    - assets/pengenalan-angka/angka-7.png
    - assets/pengenalan-angka/angka-8.png
    - assets/pengenalan-angka/angka-9.png
    - assets/pengenalan-warna/black.png
    - assets/pengenalan-warna/blue.png
    - assets/pengenalan-warna/chocolate.png
    - assets/pengenalan-warna/pink.png
    - assets/pengenalan-warna/green.png
    - assets/pengenalan-warna/grey.png
    - assets/pengenalan-warna/orange.png
    - assets/pengenalan-warna/purple.png
    - assets/pengenalan-warna/red.png
    - assets/pengenalan-warna/white.png
    - assets/pengenalan-warna/yellow.png
    - assets/pengenalan-hewan/cat.png
    - assets/pengenalan-hewan/chicken.png
    - assets/pengenalan-hewan/cow.png
    - assets/pengenalan-hewan/crab.png
    - assets/pengenalan-hewan/dog.png
    - assets/pengenalan-hewan/dolphin.png
    - assets/pengenalan-hewan/elephant.png
    - assets/pengenalan-hewan/horse.png
    - assets/pengenalan-hewan/lion.png
    - assets/pengenalan-hewan/pig.png
    - assets/pengenalan-hijaiyyah/alif.png
    - assets/pengenalan-hijaiyyah/ba.png
    - assets/pengenalan-hijaiyyah/ta.png
    - assets/pengenalan-hijaiyyah/tsa.png
    - assets/pengenalan-hijaiyyah/ja.png
    - assets/pengenalan-hijaiyyah/ha.png
    - assets/pengenalan-hijaiyyah/kha.png
    - assets/pengenalan-hijaiyyah/da.png
    - assets/pengenalan-hijaiyyah/dza.png
    - assets/pengenalan-hijaiyyah/ra.png
    - assets/pengenalan-hijaiyyah/za.png
    - assets/pengenalan-hijaiyyah/sa.png
    - assets/pengenalan-hijaiyyah/sya.png
    - assets/pengenalan-hijaiyyah/sho.png
    - assets/pengenalan-hijaiyyah/dho.png
    - assets/pengenalan-hijaiyyah/tho.png
    - assets/pengenalan-hijaiyyah/zho.png
    - assets/pengenalan-hijaiyyah/ain.png
    - assets/pengenalan-hijaiyyah/ghain.png
    - assets/pengenalan-hijaiyyah/fa.png
    - assets/pengenalan-hijaiyyah/qho.png
    - assets/pengenalan-hijaiyyah/ka.png
    - assets/pengenalan-hijaiyyah/la.png
    - assets/pengenalan-hijaiyyah/mim.png
    - assets/pengenalan-hijaiyyah/nun.png
    - assets/pengenalan-hijaiyyah/wa.png
    - assets/pengenalan-hijaiyyah/him.png
    - assets/pengenalan-hijaiyyah/lam.png
    - assets/pengenalan-hijaiyyah/hamzah.png
    - assets/pengenalan-hijaiyyah/ya.png
    
    






    
  
